/**
 * MedServerCapstone
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package project.capstone6.acne_diagnosis.models


/**
 * 
 * @param imageSource 
 * @param imageFile 
 */
data class ApiImageBody (

    val imageSource: String? = null,
    val imageFile: Array<Byte>? = null
) {
}